name: app_environment
channels:
  - snowflake
dependencies:
  - cartopy=0.24.1
  - numpy=2.2.4
  - pandas=2.2.3
  - python=3.11.*
  - seaborn=0.13.2
  - sklearn-compat=0.1.3
  - snowflake-snowpark-python=
  - statsmodels=0.14.4
  - streamlit=
